### ISSUE TITLE
About the environment of the code

### ISSUE THREAD

**Issue by OctoberKat** [prajwalsingh/EEG2Image#1]
Excellent work! I am looking forward to generate some images from EEG signals. I wonder what is the exact version of tensorflow and other packages used? Thank you!

**Comment by prajwalsingh** [comment]
Thank you for checking out our work.

We have used tensorflow-gpu 2.8 version in the conda environment with cudatoolkit=11.3.1. I have just updated the details, and you can find the anaconda environment file here: https://github.com/prajwalsingh/EEG2Image/tree/main/anaconda
