### ISSUE TITLE
Dependency Errors

### ISSUE THREAD

**Issue by nicholasshort** [prajwalsingh/EEG2Image#10]
Hello,

Great work on this project! I am trying to run it myself and am having issues with creating an environment with your yaml file:

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0

failed

CondaEnvException: Pip failed

**Comment by prajwalsingh** [comment]
Hi @nicholasshort, thank you for reading our work. 

You can comment out a few libraries if you are getting dependency errors, as CLIP is not required for this work. It's dependent on pytorch.

**Comment by nicholasshort** [comment]
Thanks for your response! I have tried commenting out the failing dependencies but it seems like there are too many failing. After commenting out the failing dependencies, I eventually arrived at this dependency conflict:

The conflict is caused by:
    The user requested transformers==4.22.1
    autogluon-text 0.4.0 depends on transformers<4.17.0 and >=4.16.2
    
I am fairly sure that both the transformers  and autogluon-text packages are required for this project. Not sure where to go from here. Do you have any ideas? Is there perhaps a working yaml file you could provide?

**Comment by prajwalsingh** [comment]
Hi @nicholasshort , this one is the working yaml. You can try the following to install the required libraries:

1. Create a new anaconda environment with python=3.9
2. Install tensorflow-gpu 2.8 [[link](https://pypi.org/project/tensorflow-gpu/2.8.0/)]
3. Then you can run the code and install missing libraries one by one.

<pre>
conda create -n tf2.8 python=3.9
conda install cudatoolkit=11.3 -c conda-forge
pip install tensorflow-gpu==2.8.0
pip install protobuf==3.19.6
</pre>

After this you have to add following in the .bashrc in case of Ubuntu or PATH in windows
<pre>export LD_LIBRARY_PATH='/home/username/anaconda3/envs/tf2.8/lib':$PATH</pre>

Restart the terminal and now you can check tensorflow-gpu:
<pre>
import tensorflow as tf
tf.config.list_physical_devices('GPU')
</pre>

Now run the code and install the missing libraries using pip one by one.

**Comment by nicholasshort** [comment]
Works thanks!
