### ISSUE TITLE
Hi, have you tried the EEGCVPR40 dataset on this work? Can the baseline in your paper, EEG2Image, generate more complicated pictures in EEGCVPR40 than those in thoutviz?

### ISSUE THREAD

**Issue by 7ASSEL** [prajwalsingh/EEG2Image#12]

**Comment by prajwalsingh** [comment]
Hi @7ASSEL , I don't remember exactly, but I tried running the code for CVPR40 at that time there was some issue with CVPR40 dataset feature extraction. Based on the past run this will not generate high resolution photorealstic images as compare to EEGStyleGAN-ADA.

**Comment by 7ASSEL** [comment]
> Hi @7ASSEL , I don't remember exactly, but I tried running the code for CVPR40 at that time there was some issue with CVPR40 dataset feature extraction. Based on the past run this will not generate high resolution photorealstic images as compare to EEGStyleGAN-ADA.

Thanks a lot! Have you done any denoising or artifact removal work to eeg data in these two papers?

**Comment by prajwalsingh** [comment]
@7ASSEL , we have used the following normalization on EEG signals before using it for training/testing:
<pre>
norm   = max(eeg) / 2.0
eeg    = (eeg - norm)/ norm
</pre>

Recently, we confirmed that it gives around a 6-7% accuracy boost.
