### ISSUE TITLE
训练时间太长怎么搞

### ISSUE THREAD

**Issue by NZW666666** [prajwalsingh/EEG2Image#13]
您好，我想问一下，训练次数300次是不是有点多，我的电脑训练一次都要几个小时，300次得训练多久啊作者？可以回复一下我吗？

**Comment by prajwalsingh** [comment]
对于训练 EEG 特征提取网络，根据您所拥有的 GPU 类型，大约需要 2-3 小时（15-20 次/秒）进行 300 个 epoch。

(For training EEG feature extraction network it would take around 2-3 hours (15-20 it/sec) for 300 epochs based on the type of GPU you have.)

**Comment by NZW666666** [comment]
那得训练好久啊，请问训练到多少轮图像才会变得清晰啊，我现在训练出来的图片基本啥都看不出来

**Comment by NZW666666** [comment]
对了，作者您好，我还想问一下运行了train.py后还需要运行哪些代码来进行测试啥的啊？感谢作者的回复，刚刚入门，还不太懂

**Comment by prajwalsingh** [comment]
我看到你在谈论训练 GAN。训练大约需要一天左右的时间，具体取决于您的计算能力（即 GPU）。经过 500-1000 轮 GAN 训练后，您将开始获取目标图像。

对于训练后的推理，您可以运行 inference.py 代码或 test_ Generation.py 代码来检查结果的输出。

(I see you are talking about training GAN. Training will take around a day or so based on your computation power, i.e., GPU. After 500-1000 epochs of GAN training, you will start getting the object image.

For inference after training, you can either run inference.py code or test_generation.py code to check the output of the results.)

**Comment by NZW666666** [comment]
哦哦好的谢谢您，我看您的原始代码是训练300轮嘛，然后我的电脑训练一轮好像要3个小时，是不是得训练好久好久：E: 3, gl: 4.535, cl: 0.318:   8%|▊         | 30/355 [16:34<2:59:51, 33.20s/it]，这个表示的是一轮吧。

**Comment by prajwalsingh** [comment]
检查您的情况是否在 GPU 上进行训练。 Tensorflow 存在 GPU 问题。根据您有关训练的信息，一次迭代大约需要 30 秒，如果我没记错的话，在我的情况下也大约需要相同的时间。经过一些迭代后，网络将开始提供不错的图像，如果没有，请检查 EEG 专长权重是否正确加载。

(Check that if training is happening on GPU or not in your case. Tensorflow has the GPU issue. Based on your information about training it is taking around 30 seconds for one iteration, If I remember correctly it was taking around the same time in my case also. The network will start giving decent images after some iterations, if not please check whether the EEG feat weights are loaded correctly or not.)

**Comment by NZW666666** [comment]
好的谢谢您的回复，我去试试
