### ISSUE TITLE
重现实验

### ISSUE THREAD

**Issue by NZW666666** [prajwalsingh/EEG2Image#15]
您好，感谢您的工作，我想问一下，如果我想用我自己的数据集重新完成整个实验，包括特征提取和用提取的特征合成图像等所有操作，该如何运行，运行哪些代码，还有对数据集的要求是什么？期待您的回复，非常非常感谢您

**Comment by NZW666666** [comment]
再次感谢您的伟大工作

**Comment by prajwalsingh** [comment]
您好，您可以浏览此问题主题，了解有关在您自己的自定义数据集上进行训练的更多详细信息 [ https://github.com/prajwalsingh/EEG2Image/issues/6 ]

(Hi, you go through this issue thread for more details about training on your own custom dataset.)

**Comment by NZW666666** [comment]
非常感谢您
