### ISSUE TITLE
What's the order of execution of codes to get the image output you got?

### ISSUE THREAD

**Issue by omamdouh123** [prajwalsingh/EEG2Image#17]

**Comment by prajwalsingh** [comment]
Hi @omamdouh123 , after downloading the checkpoint for both LSTM and GAN (or you can train it from scratch), just run the test or inference code, and it will generate the output.

**Comment by omamdouh123** [comment]
Thank you so much for replying and I apologize if my questions sound stupid. Id like to ask you if there are any tips to improve on the score or the results.

**Comment by prajwalsingh** [comment]
Hi @omamdouh123 , the only way around this is to improve representation learning strategy or use pre-trained generative model and fine tune to brain image data.
