### ISSUE TITLE
Question about the IDEs 

### ISSUE THREAD

**Issue by DungBui007** [prajwalsingh/EEG2Image#20]
Hi! 
I'm running your source code but I don't know exactly the IDE you use cuz when I run in VS Code I cant build the yml file. Can you give me the IDE you use to run this source code.
Thank you

**Comment by prajwalsingh** [comment]
Hi @DungBui007 , I, too, used VS-Code only; what you can do is install the required libraries one by one and check this issue also [[link](https://github.com/prajwalsingh/EEG2Image/issues/10)].

**Comment by DungBui007** [comment]
Thank you
