### ISSUE TITLE
关于实验的初始分数问题

### ISSUE THREAD

**Issue by NZW666666** [prajwalsingh/EEG2Image#21]
作者，您好，为什么我根据您训练的检查点文件最终得到初始分数的方差始终会比论文中的分数的方差高10倍呢，论文中都是0.05,0.04,这些，我的结果类似这种：
Inception score for epoch 0: (7.786782741546631, 0.4565214514732361)
Inception score for epoch 1: (7.721549987792969, 0.5032961368560791)
Inception score for epoch 2: (7.146868705749512, 0.5505388975143433)
Inception score for epoch 3: (7.631412506103516, 0.43543118238449097)
Inception score for epoch 4: (8.116231918334961, 0.38920989632606506)
Inception score for epoch 5: (6.84347677230835, 0.3670838475227356)
Inception score for epoch 6: (6.724668979644775, 0.7120034098625183)
Inception score for epoch 7: (7.0666351318359375, 0.48947039246559143)
Inception score for epoch 8: (6.868078708648682, 0.4820044934749603)
Inception score for epoch 9: (6.653324127197266, 0.31853899359703064)
@prajwalsingh

**Comment by NZW666666** [comment]
请问需要在意这个方差的问题吗，我怎么修改复现都还是类似的结果 @prajwalsingh

**Comment by prajwalsingh** [comment]
@NZW666666 It is expected, check this issue [[link](https://github.com/prajwalsingh/EEG2Image/issues/2)].

**Comment by NZW666666** [comment]
但是这个结果和论文EEG2IMAGE中的不太一样好像，论文中不也是用的这个thoughtvis数据集吗？那怎样才能得到论文中的初始分数呀？

**Comment by prajwalsingh** [comment]
是的，你是对的，这正是我们在这里解释的 [[link](https://github.com/prajwalsingh/EEG2Image/issues/2#issuecomment-1500075155)]

Yes you are right, this exactly what we explained here [[link](https://github.com/prajwalsingh/EEG2Image/issues/2#issuecomment-1500075155)]

**Comment by NZW666666** [comment]
好的，谢谢您的回复，但是不好意思，我没有太理解您回复的意思，我该如何得到论文中的结果呢？

**Comment by NZW666666** [comment]
我需要做哪些才能得到论文中所得到的初始分数的结果呢

**Comment by prajwalsingh** [comment]
好，我知道了;初始分数并不是衡量图像质量的良好指标。即使图像混乱，它也会给你高分；这也正是这里正在发生的事情。为了弥补这一点，我们报告了置信度得分。我们最初计划报告 FID 分数，但对于 ThoughtViz 工作，我们无法运行他们的代码，所以我们放弃了这个想法。 

您获得的结果仅对于单次或多次运行是正确的。


Ok, I got it; the inception score is not a good metric for measuring image quality. It will give you a high score even if the images are messed up; this is what exactly is happening here, also. To compensate for this, we reported the confidence score. We initially planned to report the FID score, but for ThoughtViz work, we were not able to run their code, so we dropped that idea. 

The results you are getting are correct for single or multiple runs.

**Comment by NZW666666** [comment]
好的，非常感谢你，请问在哪里能找到您报告的confidence score，我能看一下您的 FID score吗？如果我想在您的伟大工作下运行自己的数据集，我该根据什么评价指标来评价图像的好坏呢

**Comment by prajwalsingh** [comment]
Please refer to this paper and code; this is the follow-up work: Learning Robust Deep Visual Representations from EEG Brain Recordings [[link](https://arxiv.org/abs/2310.16532)]. This you can use for comparison and further experimental studies.
