### ISSUE TITLE
Choosing best checkpoint for GAN 

### ISSUE THREAD

**Issue by Cirri12** [prajwalsingh/EEG2Image#22]
Hello @prajwalsingh, I want to know how do we find the best checkpoint after training the GAN ? I trained the GAN network and all the 300 checkpoints are saved, but then how do I know the best checkpoint among them to be able to run the test_generation.py file. I ran with your provided GAN checkpoint and that ran successfully and I saw you got 210 checkpoint as the best one. So how did you arrive at that checkpoint?
Thanks for the great work!

**Comment by prajwalsingh** [comment]
Hi @Cirri12 , you must load each checkpoint and compute the inception score. The one I used gives the best inception score among all the saved checkpoints. Otherwise, you can use the updated code of EEGStyleGAN, which calculates the FID on the fly.

**Comment by Cirri12** [comment]
@prajwalsingh Thanks for the quick reply. I have one one more doubt. The checkpoint
folder you provided for GAN contains a 'checkpoint' file. It seems to have
the timestamp info of the best checkpoint only.  So I found that if I
delete this 'checkpoint' file from the folder and keep only the other two
files (ckpt-210.data-... & ckpt-210.index) and run the test_generation.py
file, then the output reconstructed image folder does not generate the
images. The images are just blank which is not the case if I use the
'checkpoint'  file. Can you please tell why this is happening? I have also
tried this with one of my own trained saved checkpoint using only the
.data- & .index file and saw the output images are either blank or just had
a light color. I did not use the saved 'checkpoint' file as it contained
all the saved checkpoints timestamps. And to get the inception score, I
think the images have to be generated properly (not blank). So how should I
get this 'checkpoint' file? Hope you are getting my problem. Maybe I am
missing something in my understanding.

**Comment by prajwalsingh** [comment]
Hi @Cirri12 , for that, don't delete the file. I tracked the file number and, based on that, removed the other timesteps. This has something to do with Tensorflow checkpoint loading method.

**Comment by Cirri12** [comment]
> Hi @Cirri12 , for that, don't delete the file. I tracked the file number and, based on that, removed the other timesteps. This has something to do with Tensorflow checkpoint loading method.

@prajwalsingh thank you so much for the clarification:) I finally got my answer why I was getting this problem.
