### ISSUE TITLE
Confusion about EEG-Image Matching

### ISSUE THREAD

**Issue by microcourier** [prajwalsingh/EEG2Image#4]
Thanks for producing this interesting paper. I have a confusion about the EEG-Image Matching part and wonder if you can clarify it.

I could not find the matching image in the EEG slices in the dataset  "eeg/image/data.pkl".
So I tried to find the answer in the code, and came down to [train.py](https://github.com/prajwalsingh/EEG2Image/blame/d73c223fb6f0480dafd8cb1d1cb6cdecf274010f/train.py#L64) 
It seems to be matching an EEG slice with a random image which is the same class. Could we only match the EEG signal to a certain class of image, or I just miss the right code？

Any clarification would be much appreciated. Thank you.

**Comment by prajwalsingh** [comment]
@microcourier Thank you for reading our work.

Yes, you are right. There is no one-to-one matching between the EEG and the image. This is due to the data acquisition step. The participants were asked to visualize one of the images from the class, and equivalent to that EEG is recorded, i.e., no specific images were shown while collecting the EEG.

**Comment by NZW666666** [comment]
您好，我可以问一下您是如何在数据集“eeg/image/data.pkl”中显示出脑电图切片的，是用什么来实现的，还有您是如何匹配的

> 感谢您撰写这篇有趣的论文。我对脑电图图像匹配部分感到困惑，想知道你是否可以澄清一下。
> 
> 我在数据集“eeg/image/data.pkl”的脑电图切片中找不到匹配的图像。所以我试图在代码中找到答案，并归结为 [train.py](https://github.com/prajwalsingh/EEG2Image/blame/d73c223fb6f0480dafd8cb1d1cb6cdecf274010f/train.py#L64) 它似乎将脑电图切片与同一类的随机图像相匹配。我们是否可以只将脑电图信号与某一类图像相匹配，或者我只是错过了正确的代码？
> 
> 如能作出任何澄清，将不胜感激。谢谢。

**Comment by prajwalsingh** [comment]
Hi @NZW666666 , 你是对的，它匹配该类的任何随机图像，因为根据数据集收集过程，没有匹配对。

(You are correct, it matches any random image of that class because as per the dataset collection procedure, there is no matching pair.)
