### ISSUE TITLE
about the checkpoint

### ISSUE THREAD

**Issue by qiuyuesong** [prajwalsingh/EEG2Image#7]
"Hello, thank you very much for your work, which has been extremely helpful to me. I am trying to reproduce your results, and I have a question regarding the LSTM model checkpoint. I noticed that there are multiple files in the path ' lstm_kmean/experiments/best_ckpt'. Can I use one of these weight files directly for EEG feature extraction, or do I need to train the LSTM model myself?"I hope it's not too presumptuous to ask, but would it be possible to share the checkpoint for your GAN network?" Thank you!"

**Comment by prajwalsingh** [comment]
Hi, 

Thank you for reading our work. 

You can use best_ckpt directly. While training the feature extraction network the accuracy was fluctuating as experience from contrastive based method. So we keep saving the best accuracy checkpoints so the checkpoint with highest accuracy is the best one. 

GAN checkpoint is already there in EEG2Image checkpoint link. LSTM checkpoint is within the LSTM folder.
