### ISSUE TITLE
Curious about hardware specs

### ISSUE THREAD

**Issue by jonxuxu** [prajwalsingh/EEG2Image#9]
Thanks for your work! I'm curious about the hardware setup you used for this project - what GPU and VRAM did you need?

**Comment by prajwalsingh** [comment]
@jonxuxu  Thank you for reading our work.

We have used two Rtx Quadro 5000 (16GB) for training the GAN network. The total VRAM takes around 12-14 GB for training with batch size 128. As we have used data distributed parallel training, so each GPU has a batch size of around 64.
